language: cpp
os: linux
dist: trusty
sudo: required
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-7
      
compiler: gcc

before_script:
  - sudo apt-get -qq update
  - sudo apt-get install -y libassimp-dev libglm-dev libsdl2-dev libsdl2-image-dev libjpeg-dev libwebp-dev libtiff5-dev

script: 
  - export CC=gcc-7
  - export CXX=g++-7
  - make
  - ./RUN.sh
  
notifications:
  email:
    recipients:
      - d3psigames@gmail.com
    on_success: always
    on_failure: always
